### PR TITLE
Implement vision potion

### PR DESCRIPTION
**Pull request by lemireg**
Create PR to see if it's passing tests.

### CODE REVIEW

**Comment by lemireg** [comment]
It looks like there is already a version of the vision potion being implemented in here.

While working it out I noticed a few things I'm going to try to fix:
the printout for the pillars doesn't go to the next line for the third part of it. i.e.
```
*-*
|M|
*-*

*-*
|E|*-*
```

I suspect the coordinates for the empty rooms are somehow not consistent with the rest of the coordinate system. I could be wrong, but I was trying to troubleshoot and was getting stuck on why empty rooms were printing in different locations than the rest.
@warlicks  fyi

**Comment by warlicks** [comment]
> It looks like there is already a version of the vision potion being implemented in here.
> 
> While working it out I noticed a few things I'm going to try to fix: the printout for the pillars doesn't go to the next line for the third part of it. i.e.
> 
> ```
> *-*
> |M|
> *-*
> 
> *-*
> |E|*-*
> ```
> 
> I suspect the coordinates for the empty rooms are somehow not consistent with the rest of the coordinate system. I could be wrong, but I was trying to troubleshoot and was getting stuck on why empty rooms were printing in different locations than the rest. @warlicks fyi

@lemireg Let my know if you want to talk through this. I wonder if there might be a way to leverage the method that prints the whole maze that I worked on this morning.

**Comment by lemireg** [comment]
> > It looks like there is already a version of the vision potion being implemented in here.
> > While working it out I noticed a few things I'm going to try to fix: the printout for the pillars doesn't go to the next line for the third part of it. i.e.
> > ```
> > *-*
> > |M|
> > *-*
> > 
> > *-*
> > |E|*-*
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I suspect the coordinates for the empty rooms are somehow not consistent with the rest of the coordinate system. I could be wrong, but I was trying to troubleshoot and was getting stuck on why empty rooms were printing in different locations than the rest. @warlicks fyi
> 
> @lemireg Let my know if you want to talk through this. I wonder if there might be a way to leverage the method that prints the whole maze that I worked on this morning.

Ya it looks like we worked on the same thing. I am working through your code to see how to integrate the two codes. From what I'm seeing we've done similar things so it will probably be just deleting one of our work. 

Do you know where the 
```
*-*
|E|
*-*
```
str representation is being created for the pillars? It is printing differently from the other objects and I can't find it in the code

**Comment by lemireg** [comment]
@warlicks wanna jump on a call to try to figure out how to combine them?

**Comment by warlicks** [comment]
https://washington.zoom.us/j/95300838097

**Comment by lemireg** [comment]
were you talking about fixing the merge conflicts between `implement_vision` branch and `main`? if so I think this is ready to merge so I"ll let you fix the merge conflicts. I'm going to try to add a test file to make sure the implementation of vision potion and healing potion are working.

**Comment by warlicks** [comment]
@lemireg Manual merge into main is done!

**Pull request closed without merging**
